channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=24.2
- pip:
  - mlflow==2.19.0
  - dagshub==0.5.1
  - pandas==2.3.2
  - scikit-learn==1.7.1
  - matplotlib==3.10.6
  - seaborn==0.13.2
name: mlflow-env